config/routes.rb
Rails.application.routes.draw do
  mount API::Base, at: "/"

  root to: "links#index"

  resources :users, only: [:new, :create]
  resources :passwords
  resource :password
  resource :session, only: [:new, :create, :delete]
  resources :links, only: [:new, :create, :index]

  get "/sign_up", to: "users#new", as: "sign_up"
  delete "/sign_out", to: "sessions#destroy", as: "sign_out"
  get "/sign_in", to: "sessions#new", as: "sign_in"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
require "uri"
require "cgi"

class Link < ApplicationRecord
  include ActiveModel::AttributeAssignment
  belongs_to :user

  validates :user, presence: true, uniqueness: { scope: :asin }
  validates :asin, presence: true

  def display_title
    self.name || "Product #{self.asin}"
  end

  def parsed_asin
    query_params["creativeASIN"][0]
  end

  def parsed_store
    query_params["tag"][0]
  end

  def self.from_url(url)
    link = Link.new(url: url)

    begin
      link.assign_attributes(asin: link.parsed_asin)
    rescue
      link.errors.add(:url, "Could not parse url")
    end

    link
  end

  private

  def query_params
    @query_params ||= CGI::parse(URI(self.url).query)
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  validates :store_id, uniqueness: true, presence: true
  validates :name, presence: true
end

app/controllers/api/base.rb
module API
  class Base < Grape::API
    mount API::V1::Base
  end
end

app/controllers/api/v1/base.rb
module API
  module V1
    class Base < Grape::API
      mount API::V1::Links
    end
  end
end

app/controllers/api/v1/defaults.rb
module API
  module V1
    module Defaults
      extend ActiveSupport::Concern

      included do
        prefix "api"
        version "v1", using: :path
        default_format :json
        format :json
        formatter :json, Grape::Formatter::ActiveModelSerializers

        helpers do
          def permitted_params
            @permitted_params ||= declared(params, 
               include_missing: false)
          end

          def logger
            Rails.logger
          end
        end

        rescue_from ActiveRecord::RecordNotFound do |e|
          error_response(message: e.message, status: 404)
        end

        rescue_from ActiveRecord::RecordInvalid do |e|
          error_response(message: e.message, status: 422)
        end
      end
    end
  end
end

app/controllers/api/v1/links.rb
module API
  module V1
    class Links < Grape::API
      include API::V1::Defaults

      resource :links do
        desc "Return all links for an ASIN"
        params do
          requires :asin, type: String, desc: "ASIN of the product"
        end
        get ":asin", root: "links" do
          Link.where(asin: permitted_params[:asin]).all
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :require_login

  def new
    @link = link_from_params
  end

  def index
    @links = Link.where(user: current_user)
  end

  def create
    @link = link_from_params

    if current_user.store_id != @link.parsed_store
      @link.errors.add(:base, "The parsed store id #{@link.parsed_store} does not match your store id #{current_user.store_id}")
    end

    if @link.save
      redirect_to links_path
    else
      if @link.errors[:user]
        # happens when the ASIN already exists for the user
        @link.errors.add(:url, "A link to this product already exists")
      end
      render "new"
    end
  end

  private

  def link_params
    params.require(:link).permit(:url, :name)
  end

  def link_from_params
    if params[:link]
      link = Link.from_url(link_params[:url])
      link.assign_attributes(user_id: current_user.id, name: link_params[:name])
      link
    else
      Link.new
    end
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < Clearance::PasswordsController
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:store_id, :name, :email, :password)
  end

  def url_after_create
    root_url
  end

  def user_from_params
    if params[:user]
      User.new(user_params)
    else
      User.new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="4.0.0";
    analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    analytics.page();
    }}();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <section class="container" id="main">
    <nav class="wrapper">
      <h1 class="nav-brand">
        <%= link_to "Link Manager", root_path %>
      </h1>

      <ul class="nav-links">
        <% if signed_in? %>
          <li>User: <%= current_user.email %></li>
          <li><%= link_to "Log Out", sign_out_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", sign_up_path %></li>
          <li><%= link_to "Log In", sign_in_path %></li>
        <% end %>
      </ul>
    </nav>
    <div class="wrapper">
      <%= render "flashes" -%>
    </div>
    <div class="wrapper">
      <%= yield %>
    </div>
  </section>
  <%= render "javascript" %>
  <%= render "css_overrides" %>
</body>
</html>

app/views/links/index.html.erb
<h2>My Links</h2>

<% if @links.any? %>
  <ul>
    <% @links.each do |link| %>
      <li><%= link_to link.display_title, link.url %></li>
    <% end %>
  </ul>

  <br/>

  <%= button_to "Add another link", new_link_path, method: :get %>
<% else %>
  <h3>
    You haven't added any links yet. <%= link_to "Add one here!", new_link_path %>
  </h3>
<% end %>

app/views/links/new.html.erb
<%= simple_form_for @link do |f| %>
  <%= f.input :name %>
  <%= f.input :url %>
  <%= f.button :submit %>
<% end %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/index.html.erb
<h1>User List</h1>
<ul>
  <% @users.each do |user| %>
    <li><%= user.store_id %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :store_id %>
  <%= f.button :submit %>
<% end %>